# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'butter.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.GrapOriginal = QtWidgets.QGraphicsView(self.centralwidget)
        self.GrapOriginal.setGeometry(QtCore.QRect(10, 10, 340, 250))
        self.GrapOriginal.setObjectName("GrapOriginal")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 20, 101, 16))
        self.label.setObjectName("label")
        self.GrapProcess = QtWidgets.QGraphicsView(self.centralwidget)
        self.GrapProcess.setGeometry(QtCore.QRect(430, 10, 340, 250))
        self.GrapProcess.setObjectName("GrapProcess")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(540, 20, 101, 16))
        self.label_2.setObjectName("label_2")
        self.BtnOriginal = QtWidgets.QPushButton(self.centralwidget)
        self.BtnOriginal.setGeometry(QtCore.QRect(110, 270, 93, 28))
        self.BtnOriginal.setObjectName("BtnOriginal")
        self.BtnProcess = QtWidgets.QPushButton(self.centralwidget)
        self.BtnProcess.setGeometry(QtCore.QRect(550, 270, 93, 28))
        self.BtnProcess.setObjectName("BtnProcess")
        self.GrapButter = QtWidgets.QGraphicsView(self.centralwidget)
        self.GrapButter.setGeometry(QtCore.QRect(430, 310, 340, 260))
        self.GrapButter.setObjectName("GrapButter")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(560, 320, 72, 15))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 360, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(90, 310, 171, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(100, 360, 51, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 390, 51, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 430, 51, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 470, 51, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 510, 51, 16))
        self.label_10.setObjectName("label_10")
        self.textFstop = QtWidgets.QTextEdit(self.centralwidget)
        self.textFstop.setGeometry(QtCore.QRect(80, 390, 81, 21))
        self.textFstop.setObjectName("textFstop")
        self.textFpass = QtWidgets.QTextEdit(self.centralwidget)
        self.textFpass.setGeometry(QtCore.QRect(80, 430, 81, 21))
        self.textFpass.setObjectName("textFpass")
        self.textAstop = QtWidgets.QTextEdit(self.centralwidget)
        self.textAstop.setGeometry(QtCore.QRect(80, 470, 81, 21))
        self.textAstop.setObjectName("textAstop")
        self.textApass = QtWidgets.QTextEdit(self.centralwidget)
        self.textApass.setGeometry(QtCore.QRect(80, 510, 81, 21))
        self.textApass.setObjectName("textApass")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(180, 390, 21, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(180, 430, 21, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(180, 470, 21, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(180, 510, 21, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(210, 390, 61, 16))
        self.label_15.setObjectName("label_15")
        self.labelN = QtWidgets.QLabel(self.centralwidget)
        self.labelN.setGeometry(QtCore.QRect(280, 390, 72, 15))
        self.labelN.setObjectName("labelN")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(210, 430, 151, 16))
        self.label_17.setObjectName("label_17")
        self.labelWn = QtWidgets.QLabel(self.centralwidget)
        self.labelWn.setGeometry(QtCore.QRect(360, 430, 61, 16))
        self.labelWn.setObjectName("labelWn")
        self.BtnButter = QtWidgets.QPushButton(self.centralwidget)
        self.BtnButter.setGeometry(QtCore.QRect(210, 500, 93, 28))
        self.BtnButter.setObjectName("BtnButter")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "巴特沃斯滤波器"))
        self.label.setText(_translate("MainWindow", "信号原始频谱"))
        self.label_2.setText(_translate("MainWindow", "信号过滤频谱"))
        self.BtnOriginal.setText(_translate("MainWindow", "绘制"))
        self.BtnProcess.setText(_translate("MainWindow", "绘制"))
        self.label_3.setText(_translate("MainWindow", "幅频响应"))
        self.label_4.setText(_translate("MainWindow", "采样频率："))
        self.label_5.setText(_translate("MainWindow", "巴特沃斯高通滤波器参数"))
        self.label_6.setText(_translate("MainWindow", "8000Hz"))
        self.label_7.setText(_translate("MainWindow", "Fstop:"))
        self.label_8.setText(_translate("MainWindow", "Fpass:"))
        self.label_9.setText(_translate("MainWindow", "Astop:"))
        self.label_10.setText(_translate("MainWindow", "Apass:"))
        self.label_11.setText(_translate("MainWindow", "Hz"))
        self.label_12.setText(_translate("MainWindow", "Hz"))
        self.label_13.setText(_translate("MainWindow", "dB"))
        self.label_14.setText(_translate("MainWindow", "dB"))
        self.label_15.setText(_translate("MainWindow", "阶数(N):"))
        self.labelN.setText(_translate("MainWindow", "example"))
        self.label_17.setText(_translate("MainWindow", "归一化截止频率(Wn):"))
        self.labelWn.setText(_translate("MainWindow", "example"))
        self.BtnButter.setText(_translate("MainWindow", "生成"))
