# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'butter1.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(487, 294)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lb_title = QtWidgets.QLabel(self.centralwidget)
        self.lb_title.setGeometry(QtCore.QRect(160, 20, 141, 16))
        self.lb_title.setObjectName("lb_title")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 60, 111, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 101, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 101, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 180, 101, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 220, 111, 16))
        self.label_5.setObjectName("label_5")
        self.textFstop = QtWidgets.QTextEdit(self.centralwidget)
        self.textFstop.setGeometry(QtCore.QRect(120, 90, 81, 31))
        self.textFstop.setObjectName("textFstop")
        self.textFpass = QtWidgets.QTextEdit(self.centralwidget)
        self.textFpass.setGeometry(QtCore.QRect(120, 130, 81, 31))
        self.textFpass.setObjectName("textFpass")
        self.textAstop = QtWidgets.QTextEdit(self.centralwidget)
        self.textAstop.setGeometry(QtCore.QRect(120, 170, 81, 31))
        self.textAstop.setObjectName("textAstop")
        self.textApass = QtWidgets.QTextEdit(self.centralwidget)
        self.textApass.setGeometry(QtCore.QRect(120, 210, 81, 31))
        self.textApass.setObjectName("textApass")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(210, 100, 21, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(210, 140, 21, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(210, 180, 21, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(210, 220, 21, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(140, 60, 81, 16))
        self.label_10.setObjectName("label_10")
        self.labelN = QtWidgets.QLabel(self.centralwidget)
        self.labelN.setGeometry(QtCore.QRect(230, 60, 72, 15))
        self.labelN.setObjectName("labelN")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(290, 60, 121, 16))
        self.label_11.setObjectName("label_11")
        self.labelWn = QtWidgets.QLabel(self.centralwidget)
        self.labelWn.setGeometry(QtCore.QRect(410, 60, 72, 15))
        self.labelWn.setObjectName("labelWn")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(240, 100, 101, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(240, 160, 121, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(240, 220, 121, 16))
        self.label_14.setObjectName("label_14")
        self.BtnOriginal = QtWidgets.QPushButton(self.centralwidget)
        self.BtnOriginal.setGeometry(QtCore.QRect(360, 90, 81, 31))
        self.BtnOriginal.setObjectName("BtnOriginal")
        self.BtnButter = QtWidgets.QPushButton(self.centralwidget)
        self.BtnButter.setGeometry(QtCore.QRect(360, 150, 81, 31))
        self.BtnButter.setObjectName("BtnButter")
        self.BtnProcess = QtWidgets.QPushButton(self.centralwidget)
        self.BtnProcess.setGeometry(QtCore.QRect(360, 210, 81, 31))
        self.BtnProcess.setObjectName("BtnProcess")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "低通滤波器的实现"))
        self.lb_title.setText(_translate("MainWindow", "巴特沃斯低通滤波器"))
        self.label.setText(_translate("MainWindow", "采样率:8000Hz"))
        self.label_2.setText(_translate("MainWindow", "阻带截止频率:"))
        self.label_3.setText(_translate("MainWindow", "通带截止频率:"))
        self.label_4.setText(_translate("MainWindow", "通带最大衰减:"))
        self.label_5.setText(_translate("MainWindow", "阻带最小衰减:"))
        self.label_6.setText(_translate("MainWindow", "Hz"))
        self.label_7.setText(_translate("MainWindow", "Hz"))
        self.label_8.setText(_translate("MainWindow", "dB"))
        self.label_9.setText(_translate("MainWindow", "dB"))
        self.label_10.setText(_translate("MainWindow", "滤波器阶数:"))
        self.labelN.setText(_translate("MainWindow", "example"))
        self.label_11.setText(_translate("MainWindow", "归一化截止频率:"))
        self.labelWn.setText(_translate("MainWindow", "example"))
        self.label_12.setText(_translate("MainWindow", "原始信号频谱:"))
        self.label_13.setText(_translate("MainWindow", "滤波器频率响应:"))
        self.label_14.setText(_translate("MainWindow", "滤波后信号频谱:"))
        self.BtnOriginal.setText(_translate("MainWindow", "绘制"))
        self.BtnButter.setText(_translate("MainWindow", "生成"))
        self.BtnProcess.setText(_translate("MainWindow", "绘制"))
